name: Update Dependencies

on:
  schedule: # Sets a schedule to trigger the workflow
    - cron: "0 8 */3 * *" # Every 3 days at 08:00 AM UTC (for more info on the cron syntax see https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule)
  workflow_dispatch: # Allows the workflow to be triggered manually via the GitHub interface

jobs:
  update_lean:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grants permission to push changes to the repository
      issues: write # Grants permission to create or update issues
      pull-requests: write # Grants permission to create or update pull requests
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Update project
        uses: leanprover-community/lean-update@v0.5.0
        with:
          on_update_succeeds: pr # Create a pull request if the update succeeds
          on_update_fails: issue # Create an issue if the update fails
          update_if_modified: lean-toolchain # Update if there is a new version of the Lean toolchain
          legacy_update: true    # Executes lake -R -Kenv=dev update instead of lake update
